use anyhow::{Context, Result};
use tokio_postgres::{error::SqlState, Client, NoTls};

#[derive(Clone, Debug)]
pub struct PgConfig {
    pub host: String,
    pub port: u16,
    pub dbname: String,
    pub user: String,
    pub password: String,
}

impl PgConfig {
    pub fn from_env() -> Self {
        let host = std::env::var("POSTGRES_HOST").unwrap_or_else(|_| "127.0.0.1".to_string());
        let port = std::env::var("POSTGRES_PORT")
            .ok()
            .and_then(|s| s.parse::<u16>().ok())
            .unwrap_or(5432);
        let dbname = std::env::var("POSTGRES_DB").unwrap_or_else(|_| "albumbud".to_string());
        let user = std::env::var("POSTGRES_USER").unwrap_or_else(|_| "m1".to_string());
        let password = std::env::var("POSTGRES_PASSWORD").unwrap_or_else(|_| "testaa".to_string());
        Self {
            host,
            port,
            dbname,
            user,
            password,
        }
    }

    pub fn to_connect_str(&self) -> String {
        format!(
            "host={} port={} dbname={} user={} password={}",
            self.host, self.port, self.dbname, self.user, self.password
        )
    }
}

/// Initialize Postgres schema per Phase 3 (tenant-first composite PKs)
pub async fn init_postgres_schema(cfg: &PgConfig) -> Result<()> {
    let (client, connection) = connect_or_create_db(cfg).await?;
    // Spawn the connection driver
    tokio::spawn(async move {
        if let Err(e) = connection.await {
            tracing::error!("Postgres connection error: {}", e);
        }
    });

    // Extensions (best-effort)
    try_exec(&client, "CREATE EXTENSION IF NOT EXISTS vector;").await;
    // VectorChord (name may vary by distro); try common names, ignore errors
    try_exec(&client, "CREATE EXTENSION IF NOT EXISTS vectorchord;").await;
    try_exec(&client, "CREATE EXTENSION IF NOT EXISTS vectordb;").await;
    try_exec(&client, "CREATE EXTENSION IF NOT EXISTS vchord;").await;

    // Control-plane
    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS organizations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    "#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            email TEXT,
            password_hash TEXT,
            oauth_provider TEXT,
            oauth_id TEXT,
            organization_id INTEGER NOT NULL REFERENCES organizations(id),
            role TEXT DEFAULT 'regular',
            avatar TEXT,
            secret TEXT,
            folders TEXT DEFAULT '',
            face_min_quality REAL DEFAULT 0.55,
            face_min_confidence REAL DEFAULT 0.75,
            face_min_size INTEGER DEFAULT 64,
            face_yaw_max REAL DEFAULT 75.0,
            face_yaw_hard_max REAL DEFAULT 85.0,
            face_min_sharpness REAL DEFAULT 0.15,
            face_sharpness_target REAL DEFAULT 500.0,
            video_face_gating_mode TEXT DEFAULT 'yolo_fallback',
            yolo_person_threshold REAL DEFAULT 0.30,
            retina_min_frames INTEGER DEFAULT 1,
            total_size BIGINT DEFAULT 0,
            trash_auto_purge_days INTEGER DEFAULT 30,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            status TEXT DEFAULT 'active',
            crypto_envelope_json TEXT,
            crypto_envelope_updated_at TIMESTAMP,
            locked_meta_allow_location BOOLEAN DEFAULT FALSE,
            locked_meta_allow_caption BOOLEAN DEFAULT FALSE,
            locked_meta_allow_description BOOLEAN DEFAULT FALSE,
            pin_hash TEXT,
            pin_remember_minutes INTEGER DEFAULT 60
        );
    "#,
    )
    .await?;

    // Best-effort backfills for deployments created before these columns existed
    // Ensure E2EE/PIN-related columns are present on existing databases
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS crypto_envelope_json TEXT",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS crypto_envelope_updated_at TIMESTAMP",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_meta_allow_location BOOLEAN DEFAULT FALSE",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_meta_allow_caption BOOLEAN DEFAULT FALSE",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_meta_allow_description BOOLEAN DEFAULT FALSE",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_hash TEXT",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_remember_minutes INTEGER DEFAULT 60",
    )
    .await;

    // Persisted indexing album options for Settings → Indexed Folders
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS index_parent_album_id INTEGER",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS index_preserve_tree_path BOOLEAN DEFAULT FALSE",
    )
    .await;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id),
            token_hash TEXT UNIQUE NOT NULL,
            expires_at TIMESTAMP NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    "#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS refresh_tokens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id),
            token_hash TEXT UNIQUE NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMP NOT NULL,
            last_used_at TIMESTAMP,
            revoked_at TIMESTAMP,
            device_id TEXT,
            user_agent TEXT
        );
    "#,
    )
    .await?;

    // Data-plane
    // Optional smart_search and text_cache tables to minimize app changes during migration
    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS smart_search (
            asset_id TEXT PRIMARY KEY,
            embedding vector(512),
            image_data BYTEA,
            image_width INTEGER,
            image_height INTEGER,
            content_type TEXT DEFAULT 'image/jpeg',
            detected_objects TEXT[],
            scene_tags TEXT[],
            search_tags TEXT[],
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    "#,
    )
    .await?;
    // Vector index for smart_search embedding (prefer VectorChord if available)
    let has_vchord = match client
        .query(
            "SELECT 1 FROM pg_extension WHERE extname IN ('vchord','vectorchord','vectordb') LIMIT 1",
            &[],
        )
        .await
    {
        Ok(rows) => !rows.is_empty(),
        Err(_) => false,
    };
    if has_vchord {
        try_exec(&client, r#"CREATE INDEX idx_smart_search_embedding ON smart_search USING vchordrq (embedding vector_cosine_ops);"#).await;
    } else {
        try_exec(&client, r#"CREATE INDEX idx_smart_search_embedding_ivf ON smart_search USING ivfflat (embedding vector_cosine_ops);"#).await;
    }
    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS text_cache (
            query_text TEXT,
            model_name TEXT,
            language TEXT,
            embedding vector(512),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (query_text, model_name, language)
        );
    "#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS photos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            organization_id INTEGER NOT NULL REFERENCES organizations(id),
            user_id TEXT NOT NULL,
            asset_id TEXT NOT NULL,
            path TEXT NOT NULL,
            filename TEXT NOT NULL,
            mime_type TEXT,
            has_gain_map BOOLEAN DEFAULT FALSE,
            hdr_kind TEXT,
            content_hash TEXT,
            content_id TEXT,
            backup_id TEXT,
            visual_backup_id TEXT,
            created_at BIGINT NOT NULL,
            modified_at BIGINT NOT NULL,
            size BIGINT NOT NULL,
            width INTEGER,
            height INTEGER,
            orientation INTEGER,
            favorites INTEGER DEFAULT 0,
            rating SMALLINT,
            locked BOOLEAN DEFAULT FALSE,
            is_video BOOLEAN DEFAULT FALSE,
            is_live_photo BOOLEAN DEFAULT FALSE,
            live_video_path TEXT,
            duration_ms BIGINT DEFAULT 0,
            delete_time BIGINT NOT NULL DEFAULT 0,
            is_screenshot INTEGER DEFAULT 0,
            camera_make TEXT,
            camera_model TEXT,
            iso INTEGER,
            aperture REAL,
            shutter_speed TEXT,
            focal_length REAL,
            latitude REAL,
            longitude REAL,
            altitude REAL,
            location_name TEXT,
            city TEXT,
            province TEXT,
            country TEXT,
            caption TEXT,
            description TEXT,
            comments TEXT,
            likes TEXT,
            ocr_text TEXT,
            search_indexed_at BIGINT,
            last_indexed BIGINT NOT NULL,
            crypto_version INTEGER DEFAULT 0,
            locked_orig_uploaded BOOLEAN DEFAULT FALSE,
            locked_thumb_uploaded BOOLEAN DEFAULT FALSE,
            UNIQUE(id),
            PRIMARY KEY (organization_id, asset_id)
        );
    "#,
    )
    .await?;
    // Best-effort migrations for older deployments
    try_exec(
        &client,
        "ALTER TABLE photos ADD COLUMN IF NOT EXISTS locked_orig_uploaded BOOLEAN DEFAULT FALSE;",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE photos ADD COLUMN IF NOT EXISTS locked_thumb_uploaded BOOLEAN DEFAULT FALSE;",
    )
    .await;
    exec(&client, r#"CREATE UNIQUE INDEX IF NOT EXISTS idx_photos_org_asset ON photos(organization_id, asset_id);"#).await?; // supports ON CONFLICT for legacy DBs
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photos_org_created ON photos(organization_id, created_at);"#).await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_photos_org_locked ON photos(organization_id, locked);"#,
    )
    .await?;
    try_exec(
        &client,
        "ALTER TABLE photos ADD COLUMN IF NOT EXISTS backup_id TEXT;",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE photos ADD COLUMN IF NOT EXISTS visual_backup_id TEXT;",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE photos ADD COLUMN IF NOT EXISTS has_gain_map BOOLEAN DEFAULT FALSE;",
    )
    .await;
    try_exec(
        &client,
        "ALTER TABLE photos ADD COLUMN IF NOT EXISTS hdr_kind TEXT;",
    )
    .await;
    try_exec(
        &client,
        "CREATE INDEX IF NOT EXISTS idx_photos_backup_id ON photos(backup_id);",
    )
    .await;
    try_exec(
        &client,
        "CREATE INDEX IF NOT EXISTS idx_photos_visual_backup_id ON photos(visual_backup_id);",
    )
    .await;
    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS deleted_upload_tombstones (
            organization_id INTEGER NOT NULL REFERENCES organizations(id),
            user_id TEXT NOT NULL,
            key_kind TEXT NOT NULL,
            key_value TEXT NOT NULL,
            source_asset_id TEXT NOT NULL,
            deleted_at BIGINT NOT NULL,
            PRIMARY KEY (organization_id, user_id, key_kind, key_value)
        );
    "#,
    )
    .await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_deleted_upload_tombstones_source ON deleted_upload_tombstones(organization_id, user_id, source_asset_id);"#,
    )
    .await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photos_org_deleted ON photos(organization_id, delete_time);"#).await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_photos_org_video ON photos(organization_id, is_video);"#,
    )
    .await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photos_org_filename ON photos(organization_id, filename);"#).await?;

    exec(&client, r#"
        CREATE TABLE IF NOT EXISTS photo_embeddings (
            organization_id INTEGER NOT NULL,
            asset_id TEXT NOT NULL,
            clip_image vector(512) NOT NULL,
            clip_text vector(512),
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (organization_id, asset_id),
            FOREIGN KEY (organization_id, asset_id) REFERENCES photos(organization_id, asset_id) ON DELETE CASCADE
        );
    "#)
    .await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_pe_org ON photo_embeddings(organization_id);"#,
    )
    .await?;
    // Photo embeddings: prefer VectorChord; fallback to ivfflat
    if has_vchord {
        try_exec(&client, r#"CREATE INDEX idx_pe_clip ON photo_embeddings USING vchordrq (clip_image vector_cosine_ops);"#).await;
    } else {
        try_exec(&client, r#"CREATE INDEX idx_pe_clip_ivf ON photo_embeddings USING ivfflat (clip_image vector_cosine_ops);"#).await;
    }

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS faces (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            face_id TEXT NOT NULL,
            organization_id INTEGER NOT NULL,
            asset_id TEXT NOT NULL,
            person_id TEXT NULL,
            bbox_x INTEGER,
            bbox_y INTEGER,
            bbox_width INTEGER,
            bbox_height INTEGER,
            confidence REAL,
            embedding vector(512),
            face_thumbnail BYTEA,
            quality_score REAL,
            yaw_deg REAL,
            sharpness REAL,
            is_hidden BOOLEAN DEFAULT FALSE,
            time_ms BIGINT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(id),
            UNIQUE(face_id),
            PRIMARY KEY (organization_id, face_id)
        );
    "#,
    )
    .await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_faces_org_person ON faces(organization_id, person_id);"#,
    )
    .await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_faces_org_asset ON faces(organization_id, asset_id);"#,
    )
    .await?;
    // Faces: prefer VectorChord; fallback to ivfflat
    if has_vchord {
        try_exec(&client, r#"CREATE INDEX idx_faces_embedding ON faces USING vchordrq (embedding vector_cosine_ops);"#).await;
    } else {
        try_exec(&client, r#"CREATE INDEX idx_faces_embedding_ivf ON faces USING ivfflat (embedding vector_cosine_ops);"#).await;
    }

    // Persons table (names, representative face, counts)
    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS persons (
            organization_id INTEGER NOT NULL,
            person_id TEXT NOT NULL,
            display_name TEXT,
            birth_date TEXT,
            face_count INTEGER DEFAULT 0,
            representative_face_id TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (organization_id, person_id)
        );
    "#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS face_photos (
            face_id INTEGER NOT NULL REFERENCES faces(id) ON DELETE CASCADE,
            photo_id INTEGER NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
            organization_id INTEGER NOT NULL,
            confidence REAL,
            bbox_x INTEGER,
            bbox_y INTEGER,
            bbox_width INTEGER,
            bbox_height INTEGER,
            age_in_photo REAL,
            PRIMARY KEY (organization_id, face_id, photo_id)
        );
    "#,
    )
    .await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_fp_org ON face_photos(organization_id);"#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS albums (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY,
            organization_id INTEGER NOT NULL,
            user_id TEXT NOT NULL,
            name TEXT NOT NULL,
            name_lc TEXT,
            description TEXT,
            parent_id INTEGER REFERENCES albums(id) ON DELETE SET NULL,
            position INTEGER,
            cover_photo_id INTEGER REFERENCES photos(id),
            is_live BOOLEAN DEFAULT FALSE,
            live_criteria TEXT,
            photo_count INTEGER DEFAULT 0,
            deleted_at BIGINT,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            UNIQUE (parent_id, name),
            UNIQUE (id),
            PRIMARY KEY (organization_id, id)
        );
    "#,
    )
    .await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_albums_org_parent ON albums(organization_id, parent_id);"#).await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS album_photos (
            organization_id INTEGER NOT NULL,
            album_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
            photo_id INTEGER NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
            added_at BIGINT NOT NULL,
            position INTEGER,
            PRIMARY KEY (organization_id, album_id, photo_id)
        );
    "#,
    )
    .await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_album_photos_org ON album_photos(organization_id);"#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS album_closure (
            organization_id INTEGER NOT NULL,
            ancestor_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
            descendant_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
            depth INTEGER NOT NULL,
            PRIMARY KEY (organization_id, ancestor_id, descendant_id)
        );
    "#,
    )
    .await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_ac_org ON album_closure(organization_id);"#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS yolo_detections (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            photo_id INTEGER NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
            organization_id INTEGER NOT NULL,
            label TEXT,
            confidence REAL,
            bbox_x REAL,
            bbox_y REAL,
            bbox_width REAL,
            bbox_height REAL
        );
    "#,
    )
    .await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_yolo_org_label ON yolo_detections(organization_id, label);"#).await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS photo_hashes (
            organization_id INTEGER NOT NULL,
            asset_id TEXT NOT NULL,
            phash_hex TEXT NOT NULL,
            UNIQUE(organization_id, asset_id)
        );
    "#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS video_phash_samples (
            organization_id INTEGER NOT NULL,
            asset_id TEXT NOT NULL,
            sample_idx SMALLINT NOT NULL,
            pos_pct REAL,
            time_ms BIGINT,
            phash_hex TEXT NOT NULL,
            PRIMARY KEY (organization_id, asset_id, sample_idx)
        );
    "#,
    )
    .await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_video_phash_org_asset ON video_phash_samples(organization_id, asset_id);"#).await?;
    exec(
        &client,
        r#"CREATE INDEX IF NOT EXISTS idx_video_phash_hex ON video_phash_samples(phash_hex);"#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS geocode_cache (
            organization_id INTEGER NOT NULL,
            key TEXT NOT NULL,
            lat REAL,
            lon REAL,
            precision INTEGER,
            location_name TEXT,
            city TEXT,
            province TEXT,
            country TEXT,
            updated_at BIGINT,
            UNIQUE(organization_id, key)
        );
    "#,
    )
    .await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS photo_comments (
            organization_id INTEGER NOT NULL,
            id TEXT NOT NULL,
            asset_id TEXT NOT NULL,
            scope TEXT NOT NULL,
            author_display_name TEXT,
            author_user_id TEXT,
            viewer_session_id TEXT,
            body TEXT NOT NULL,
            created_at BIGINT NOT NULL,
            PRIMARY KEY (organization_id, id)
        );
    "#,
    )
    .await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photo_comments_org_asset ON photo_comments(organization_id, asset_id);"#).await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photo_comments_asset_scope ON photo_comments(asset_id, scope);"#).await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photo_comments_scope_created ON photo_comments(scope, created_at DESC);"#).await?;

    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS photo_likes (
            organization_id INTEGER NOT NULL,
            asset_id TEXT NOT NULL,
            scope TEXT NOT NULL,
            actor TEXT NOT NULL,
            created_at BIGINT NOT NULL,
            PRIMARY KEY (organization_id, asset_id, scope, actor)
        );
    "#,
    )
    .await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photo_likes_org_asset ON photo_likes(organization_id, asset_id);"#).await?;
    exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_photo_likes_asset_scope ON photo_likes(asset_id, scope);"#).await?;

    // EE organization settings (public link URL prefix, etc.)
    exec(
        &client,
        r#"
        CREATE TABLE IF NOT EXISTS ee_org_settings (
            organization_id INTEGER NOT NULL,
            key TEXT NOT NULL,
            value TEXT,
            PRIMARY KEY (organization_id, key)
        );
    "#,
    )
    .await?;

    // EE user keypairs for share E2EE (public/shared scopes)
    #[cfg(feature = "ee")]
    {
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_user_keypairs (
                user_id TEXT PRIMARY KEY,
                pubkey_b64 TEXT NOT NULL,
                curve TEXT DEFAULT 'P-256',
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        "#,
        )
        .await?;
    }

    // EE: Sharing + Public Links control-plane tables
    #[cfg(feature = "ee")]
    {
        // Shares (account/internal sharing)
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_shares (
                id TEXT PRIMARY KEY,
                owner_org_id INTEGER NOT NULL,
                owner_user_id TEXT NOT NULL,
                object_kind TEXT NOT NULL,
                object_id TEXT NOT NULL,
                default_permissions INTEGER NOT NULL DEFAULT 1,
                expires_at TIMESTAMP,
                status TEXT DEFAULT 'active',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                name TEXT DEFAULT '' NOT NULL,
                include_faces BOOLEAN DEFAULT TRUE NOT NULL,
                include_subtree BOOLEAN DEFAULT FALSE NOT NULL
            );
        "#,
        )
        .await?;
        // Best-effort migrations for existing deployments that may have older types
        // Ensure default_permissions has the correct INTEGER type (avoid serialization errors)
        try_exec(&client, "ALTER TABLE ee_shares ALTER COLUMN default_permissions TYPE INTEGER USING default_permissions::INTEGER;");
        // Ensure boolean columns have the correct type when present
        try_exec(&client, "ALTER TABLE ee_shares ALTER COLUMN include_faces TYPE BOOLEAN USING COALESCE(include_faces::BOOLEAN, TRUE);");
        try_exec(&client, "ALTER TABLE ee_shares ALTER COLUMN include_subtree TYPE BOOLEAN USING COALESCE(include_subtree::BOOLEAN, FALSE);");
        exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_ee_share_owner ON ee_shares(owner_org_id, owner_user_id);"#).await?;
        exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_ee_share_object ON ee_shares(object_kind, object_id);"#).await?;
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_share_recipients (
                id TEXT PRIMARY KEY,
                share_id TEXT NOT NULL REFERENCES ee_shares(id) ON DELETE CASCADE,
                recipient_type TEXT NOT NULL,
                recipient_user_id TEXT,
                recipient_group_id INTEGER,
                external_email TEXT,
                external_org_id INTEGER,
                permissions INTEGER,
                invitation_status TEXT DEFAULT 'active',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        "#,
        )
        .await?;
        exec(&client, r#"CREATE UNIQUE INDEX IF NOT EXISTS idx_ee_share_recipient_dedupe ON ee_share_recipients(share_id, recipient_type, COALESCE(recipient_user_id, CAST(recipient_group_id AS TEXT), external_email));"#).await?;
        // Per-recipient SMK envelopes for share E2EE
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_shares_recipient_smk_envelopes (
                share_id TEXT NOT NULL REFERENCES ee_shares(id) ON DELETE CASCADE,
                recipient_user_id TEXT NOT NULL,
                smk_envelope_json TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (share_id, recipient_user_id)
            );
        "#,
        )
        .await?;
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_share_activity (
                id TEXT PRIMARY KEY,
                share_id TEXT NOT NULL REFERENCES ee_shares(id) ON DELETE CASCADE,
                actor_user_id TEXT,
                event TEXT NOT NULL,
                at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                meta TEXT
            );
        "#,
        )
        .await?;

        // Public links
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_public_links (
                id TEXT PRIMARY KEY,
                owner_org_id INTEGER NOT NULL,
                owner_user_id TEXT NOT NULL,
                name TEXT NOT NULL,
                scope_kind TEXT NOT NULL,
                scope_album_id INTEGER,
                uploads_album_id INTEGER,
                key_hash TEXT,
                key_plain TEXT,
                pin_hash TEXT,
                permissions INTEGER NOT NULL,
                expires_at TIMESTAMP,
                status TEXT NOT NULL DEFAULT 'active',
                cover_asset_id TEXT NOT NULL,
                moderation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        "#,
        )
        .await?;
        exec(&client, r#"CREATE INDEX IF NOT EXISTS ee_public_links_owner_idx ON ee_public_links(owner_org_id, owner_user_id);"#).await?;
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_public_link_assets (
                link_id TEXT NOT NULL REFERENCES ee_public_links(id) ON DELETE CASCADE,
                asset_id TEXT NOT NULL,
                position INTEGER,
                PRIMARY KEY (link_id, asset_id)
            );
        "#,
        )
        .await?;
        exec(&client, r#"CREATE INDEX IF NOT EXISTS ee_public_link_assets_pos ON ee_public_link_assets(link_id, position);"#).await?;
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_public_links_smk_envelopes (
                link_id TEXT PRIMARY KEY REFERENCES ee_public_links(id) ON DELETE CASCADE,
                smk_envelope_json TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        "#,
        )
        .await?;
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS ee_public_link_uploads (
                link_id TEXT NOT NULL REFERENCES ee_public_links(id) ON DELETE CASCADE,
                asset_id TEXT NOT NULL,
                status TEXT NOT NULL,
                viewer_session_id TEXT,
                uploader_display_name TEXT,
                created_at BIGINT,
                PRIMARY KEY (link_id, asset_id)
            );
        "#,
        )
        .await?;
        exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_eplu_status ON ee_public_link_uploads(link_id, status, created_at);"#).await?;

        // E2EE wraps shared between public links and shares
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS locked_dek_wraps (
                owner_user_id TEXT NOT NULL,
                scope_key TEXT NOT NULL,
                asset_id TEXT NOT NULL,
                variant TEXT NOT NULL,
                wrap_iv_b64 TEXT NOT NULL,
                dek_wrapped_b64 TEXT NOT NULL,
                encrypted_by_user_id TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (owner_user_id, scope_key, asset_id, variant)
            );
        "#,
        )
        .await?;
        exec(&client, r#"CREATE INDEX IF NOT EXISTS idx_locked_dek_wraps_scope ON locked_dek_wraps(scope_key, asset_id);"#).await?;
    }

    // EE: users table extra columns (if not present)
    try_exec(
        &client,
        r#"ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN DEFAULT FALSE;"#,
    )
    .await;
    try_exec(
        &client,
        r#"ALTER TABLE users ADD COLUMN IF NOT EXISTS token_version INTEGER DEFAULT 1;"#,
    )
    .await;

    // EE: Groups and membership tables
    #[cfg(feature = "ee")]
    {
        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS groups (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id INTEGER NOT NULL REFERENCES organizations(id),
                name TEXT NOT NULL,
                description TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                deleted_at TIMESTAMP
            );
        "#,
        )
        .await?;
        exec(
            &client,
            r#"CREATE INDEX IF NOT EXISTS idx_groups_org_name ON groups(organization_id, name);"#,
        )
        .await?;

        exec(
            &client,
            r#"
            CREATE TABLE IF NOT EXISTS user_groups (
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (user_id, group_id)
            );
        "#,
        )
        .await?;
    }

    tracing::info!("Postgres schema initialized (Phase 3)");
    Ok(())
}

async fn exec(client: &Client, sql: &str) -> Result<u64> {
    client
        .execute(sql, &[])
        .await
        .with_context(|| format!("Failed to execute SQL: {}", sql))
}

async fn try_exec(client: &Client, sql: &str) {
    if let Err(e) = client.execute(sql, &[]).await {
        tracing::debug!("Ignoring SQL error: {} => {}", sql, e);
    }
}

async fn connect_or_create_db(
    cfg: &PgConfig,
) -> Result<(
    Client,
    tokio_postgres::Connection<tokio_postgres::Socket, tokio_postgres::tls::NoTlsStream>,
)> {
    match tokio_postgres::connect(&cfg.to_connect_str(), NoTls).await {
        Ok((client, conn)) => Ok((client, conn)),
        Err(e) => {
            // Robustly detect "database does not exist" across environments
            let mut is_missing_db = false;
            if let Some(db_err) = e.as_db_error() {
                if db_err.code() == &SqlState::INVALID_CATALOG_NAME {
                    // 3D000: invalid_catalog_name → database does not exist
                    is_missing_db = true;
                }
            }
            let msg = format!("{}", e);
            let msg_lc = msg.to_lowercase();
            if msg_lc.contains("does not exist")
                || msg_lc.contains("unknown database")
                || msg_lc.contains("invalid catalog name")
            {
                is_missing_db = true;
            }

            if is_missing_db {
                // Try to create the database by connecting to the default postgres DB
                let admin_conn_str = format!(
                    "host={} port={} dbname=postgres user={} password={}",
                    cfg.host, cfg.port, cfg.user, cfg.password
                );
                let (admin_client, admin_conn) = tokio_postgres::connect(&admin_conn_str, NoTls)
                    .await
                    .with_context(|| "Failed to connect to Postgres (postgres db)")?;
                // Drive admin connection
                tokio::spawn(async move {
                    if let Err(e) = admin_conn.await {
                        tracing::error!("Postgres admin connection error: {}", e);
                    }
                });
                let create_sql = format!("CREATE DATABASE {}", cfg.dbname);
                // Best-effort create; ignore if race
                if let Err(err) = admin_client.execute(&create_sql, &[]).await {
                    let emsg = format!("{}", err);
                    if !(emsg.contains("already exists") || emsg.contains("duplicate")) {
                        return Err(anyhow::anyhow!(
                            "Failed to create database {}: {}",
                            cfg.dbname,
                            err
                        ));
                    }
                }
                // Reconnect to target DB
                tokio_postgres::connect(&cfg.to_connect_str(), NoTls)
                    .await
                    .with_context(|| "Failed to connect to Postgres after creating DB")
            } else {
                Err(anyhow::anyhow!("db error: {} | debug: {:?}", e, e))
            }
        }
    }
}
